name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
        poetry-version: [1.5.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: make cover
